name: Publish NuGet

on:
  release:
    types: [published]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      # Build the release build
      - run: dotnet build -c Release

      # Now build a linux publish
      - run: dotnet test -c Release
      - name: Publish to NuGet
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: UglyToad.WiseOak/UglyToad.WiseOak.csproj
          VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
          PACKAGE_NAME: WiseOak
          TAG_FORMAT: "*"
          NUGET_KEY: ${{secrets.NUGET_KEY}}
